### ISSUE TITLE
Inconsistent Training Parameters in 'trainer_state' and Reproduction Issues

### ISSUE THREAD

**Issue by Molly-3000** [RLHF-V/RLAIF-V#27]
Hi!

Thank you for open-sourcing your great work!

I'm having some trouble reproducing the results from the paper. I trained LLaVA 1.5-7B for 4 iterations, using parquet files sequentially from parquet-006 to parquet-009, one by one. However, the evaluation results of the final model are quite different from those of the released model.

For each iteration, I used 8 A100 GPUs with `num_train_epochs=4`, `per_device_train_batch_size=1`, `gradient_accumulation_steps=1`, `learning_rate=5e-7`, and `dpo_beta=0.1`, as specified in the paper.

I noticed that the parameters in the released [trainer_state](https://huggingface.co/openbmb/RLAIF-V-7B/blob/main/trainer_state.json) do not match the settings above. For example, it appears that the training stopped at `epoch=2.25` and `step=1692`, which does not satisfy either `max_steps=3008` or `num_train_epochs=4`.

Any additional details would be greatly appreciated. Thank you! @Haoye17

**Comment by Haoye17** [comment]
Hi @Molly-3000 ,

Thank you for your interest~ 

For each iteration, we save every 1/4 epoch in the whole process of training, and we use the Object HalBench and MMHal Bench as the validation for checkpoint selection, so the final checkpoint may not be the checkpoint at the 4th epoch. 

Meanwhile, directly using the 2nd, 3rd, and 4th iteration data in our dataset may not provide an excellent performance since your model after the previous training iteration can be different from our data generation model due to the randomness in training. This may cause a distribution shift between your base model and the training data.

To reach the best performance, we advise you to generate new pairs for your models in each iteration following the instructions [here](https://github.com/RLHF-V/RLAIF-V/blob/main/README.md#data-generation).
